name: Release

# Run this workflow every time a new commit pushed to your repository
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master

jobs:
  build:
    name: build and release the app
    runs-on: ubuntu-latest
    container:
      image: coatldev/six:3.10.11a9

    steps:
      - name: set env
        run: echo "NOW=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Python2
        uses: actions/setup-python@v5
        with:
          python-version: '2.7.18'

      - name: setup ionic and cordova
        uses: coturiv/setup-ionic@v1.0.4
        with:
          cordova-version: 8
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Checkout code
        uses: actions/checkout@v2
      - run: npm ci
      - run: ionic cordova build android --confirm --no-interactive --verbose
      - name: Create the new Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "/home/runner/work/escolhinha/escolhinha/platforms/android/app/build/outputs/apk/debug/app-debug.apk"
          body: "Escolinha release"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.NOW }}
          commit: master
          draft: false
